# Generated by Django 3.1.2 on 2020-10-24 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='image',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='vrml_id',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
    ]
