# Generated by Django 3.1.2 on 2020-10-24 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_auto_20201024_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='vrml_id',
            field=models.CharField(max_length=32),
        ),
    ]
