# Generated by Django 3.1.2 on 2020-11-02 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_auto_20201024_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='seeded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='card',
            name='vrml_id',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
