# Generated by Django 3.1.2 on 2020-11-04 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201029_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.CharField(default='https://cdnb.artstation.com/p/assets/images/images/012/391/405/large/miguel-vasquez-887.jpg?1534543934', max_length=255),
            preserve_default=False,
        ),
    ]
